DAte + Mahasiswa array and array index

In [3]:
import datetime

aList = ["John", 33, "Toronto", True]
print(aList)

x = datetime.date.today()
date = x.strftime("%d-%m-%Y")
mahasiswa = ["Rafael Octo", 2024071003, "Informatika", "DAA", date, "Universitas Pembangunan Jaya"]
print(mahasiswa)

print(mahasiswa[1]) # NIM

['John', 33, 'Toronto', True]
['Rafael Octo', 2024071003, 'Informatika', 'DAA', '15-09-2025', 'Universitas Pembangunan Jaya']
2024071003


Slicing & Iterate

In [11]:
print(mahasiswa[1:3], "Slicing") #Slicing
print(mahasiswa[2:1], "Slicing") #Slicing

for i in mahasiswa: #Iterasi
    print(i, "UPJ")

[2024071003, 'Informatika'] Slicing
[] Slicing
Rafael Octo UPJ
2024071003 UPJ
Informatika UPJ
DAA UPJ
15-09-2025 UPJ
Universitas Pembangunan Jaya UPJ


In [ ]:
color_tuple = ["Red", "Green", "Blue","yellow"]
for i in color_tuple:
    print(i, "Square")

Red (Color)
Green (Color)
Blue (Color)
yellow (Color)


Tuple dan nested Tuple

In [20]:
color_tuple = ("Red", "Green", "Blue","yellow")
print(color_tuple[1])
color_tuple[2:]

Green


('Blue', 'yellow')

In [24]:
# This is a tuple.
upj = ('Universitas', 'pembangunan jaya')
print(upj)

# You can also have a tuple within another tuple.
nested_tuple = (100, (200,400,600), 300, (400,800))
print(nested_tuple[1][0]) # This will print '200' from the nested tuple

('Universitas', 'pembangunan jaya')
200


Dictionary

In [25]:
bin_colors = {
 "Manual_color" : "Yellow",
 "Approved_color" : "Green",
 "ReUsed_color" : "Red",
}
print(bin_colors)

{'Manual_color': 'Yellow', 'Approved_color': 'Green', 'ReUsed_color': 'Red'}


In [23]:
mahasiswa = {
    "nama" : "Rafael Octo",
    "NIM" : 2024071003,
    "Prodi" : "Informatika",
    "Universitas" : "UPJ",
}
print(mahasiswa)


{'nama': 'Rafael Octo', 'NIM': 2024071003, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


Set Red dan Yellow

In [7]:
red = {'blood', 'rose', 'fire hydrant', 'leaves'}
yellow = {'dandelion', 'fire hydrant', 'leaves'}
print(red|yellow) #union
print(red&yellow) #intersection

{'leaves', 'blood', 'rose', 'fire hydrant', 'dandelion'}
{'fire hydrant', 'leaves'}


DataFrames

In [24]:
# pandas has not been imported yet in previous cells, so we need to import it here
import pandas as pd
df = pd.DataFrame([
    [1, 'Fares', 32, True],
    [2, 'Elena', 23, False],
    [3, 'Steven', 40, True]
])
df.columns = ['ID', 'Name', 'Age', 'Desicion']
df[['Name','Age']]
# df.iloc[0:3]
# df[df.Age > 30]
df[(df.Age<35)&(df.Desicion==True)]

ID   Name  Age  Desicion
0   1  Fares   32      True

In [22]:
DB_Mahasiswa = pd.DataFrame([
    ["1", "Informatika", 50, 30, 20],
    ["2", "Sistem Informasi", 50, 30, 25],
    ["3", "Teknik Sipil", 50, 30, 10],
])
DB_Mahasiswa.columns = ['No', 'Prodi', 'Mahasiswa', 'Laki-laki', 'Perempuan']
DB_Mahasiswa

No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         50         30         25
2  3      Teknik Sipil         50         30         10

Matrix

In [25]:
import numpy as np
myMatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [ ]:
myMatrix = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
anArray = np.array([])
for i in Myma):
    for j in range(myMatrix):
        anArray = np.append(anArray, myMatrix[i][j])
print(anArray)
          

TypeError: only integer scalar arrays can be converted to a scalar index